---
- name: Install Code OSS
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - code # The Open Source build of Visual Studio Code (vscode) editor
  tags:
    - install-code

- name: Enable GTK dialogs for Code OSS
  ansible.builtin.replace:
    path: /usr/share/applications/code-oss.desktop
    regexp: "^Exec(.+)$"
    replace: "Exec=env GTK_USE_PORTAL=1 /usr/bin/code-oss"
  tags:
    - configure-code

- name: Install Code OSS extension
  become: false
  ansible.builtin.shell: /usr/bin/code-oss --install-extension {{ item }}
  with_items:
    - arcticicestudio.nord-visual-studio-code
    - bierner.markdown-mermaid
    - esbenp.prettier-vscode
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-python.black-formatter
    - llvm-vs-code-extensions.vscode-clangd
    - pkief.material-icon-theme
    - redhat.vscode-yaml
    - rust-lang.rust-analyzer
    - tamasfe.even-better-toml
    - tht13.python
    - yzhang.markdown-all-in-one
  changed_when: false
  tags:
    - install-code-extensions

- name: Copy User Settings
  ansible.builtin.template:
    src: settings.json
    dest: "{{ settings_path }}"
    force: true
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'