---
- name: Install Python
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - bpython # Fancy ncurses interface to the Python interpreter
    - python # Next generation of the python high-level scripting language
    - python-django # A high-level Python Web framework that encourages rapid development and clean design
    - python-google-auth # Google Authentication Library
    - python-jedi # Awesome autocompletion for python
    - python-lsp-server # Fork of the python-language-server project, maintained by the Spyder IDE team and the community
    - python-pip # The PyPA recommended tool for installing Python packages
  tags:
    - installation-python
