---
- name: Install X11
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - xorg
    - xorg-apps
    - xorg-docs
    - xorg-xinit # X.Org initialisation program
    - xorg-server # Xorg X server
  tags:
    - install-x11