- name: Install miscellaneous apps
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - ffmpegthumbs # FFmpeg-based thumbnail creator for video files
    - firefox # Standalone web browser from mozilla.org
    - freerdp # Free implementation of the Remote Desktop Protocol (RDP)
    - lapce # Lightning-fast and Powerful Code Editor
    - mariadb-clients # MariaDB client tools
    - postgresql-libs # Libraries for use with PostgreSQL
    - sqlite # A C library that implements an SQL database engine
    - telegram-desktop # Official Telegram Desktop client
    - tor # Anonymizing overlay network
    - torbrowser-launcher # Securely and easily download, verify, install, and launch Tor Browser in Linux
    - vlc # Multi-platform MPEG, VCD/DVD, and DivX player
    - yt-dlp # A youtube-dl fork with additional features and fixes
  tags:
    - installation-misc
  